spring.profiles.active=prod
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

# JWT
jwt.secret=${JWT_SECRET}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never